/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherlogger;

/**
 *
 * @author Marc
 */
import javax.swing.table.DefaultTableModel;

public class StatsUI extends javax.swing.JFrame {

    private String[][] tableData;
    private String[] row;
    private final FileRead textRead = new FileRead();
    private final JDBCRead dbRead = new JDBCRead();
    private final AverageTemperature tempAvg = new AverageTemperature();
    private final AverageSpeed speedAvg = new AverageSpeed();
    private String time;    
    
    /**
     * Creates new form StatsUI
     */
    public StatsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        windLabel = new javax.swing.JLabel();
        windField = new javax.swing.JTextField();
        windCombo = new javax.swing.JComboBox();
        tempField = new javax.swing.JTextField();
        tempCombo = new javax.swing.JComboBox();
        tempLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        degreeLabel = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        recordItem = new javax.swing.JMenuItem();
        statsItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        LocaleButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dateField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        textfileRadioButton = new javax.swing.JRadioButton();
        databaseRadioButton = new javax.swing.JRadioButton();
        localeLabel = new javax.swing.JLabel();
        avSpeedLabel = new javax.swing.JLabel();
        avTempLabel = new javax.swing.JLabel();
        avTempTextField = new javax.swing.JTextField();
        avSpeedTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mainItem = new javax.swing.JMenuItem();
        optionsItem2 = new javax.swing.JMenuItem();
        exitItem2 = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setResizable(false);

        jButton1.setText("Record");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1startReading(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2stopReading(evt);
            }
        });

        windLabel.setText("Wind Speed");

        windField.setEditable(false);

        windCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilometers/h", "Miles/h" }));

        tempField.setEditable(false);

        tempCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celsius", "Fahrenheit" }));
        tempCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempComboActionPerformed(evt);
            }
        });

        tempLabel.setText("Temperature");

        speedLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedLabel.setText("Kph");

        degreeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        degreeLabel.setText("'C");

        jMenu2.setText("File");

        recordItem.setText("Record");
        jMenu2.add(recordItem);

        statsItem.setText("Stats");
        jMenu2.add(statsItem);

        exitItem.setText("Exit");
        jMenu2.add(exitItem);

        jMenuBar2.add(jMenu2);

        jFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tempLabel)
                            .addComponent(windLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tempCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tempField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(windCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(windField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedLabel)
                            .addComponent(degreeLabel))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windLabel)
                    .addComponent(speedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempLabel)
                    .addComponent(degreeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(420, 455));
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Wind Speed", "Temperature"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        dateLabel.setText("Date(yyyy/mm/dd)");

        LocaleButtonGroup.add(textfileRadioButton);
        textfileRadioButton.setText("Textfile");
        textfileRadioButton.setToolTipText("");

        LocaleButtonGroup.add(databaseRadioButton);
        databaseRadioButton.setText("Database");

        localeLabel.setText("Location of the data");

        avSpeedLabel.setText("Average wind speed:");

        avTempLabel.setText("Average Temperature:");

        avTempTextField.setEditable(false);

        avSpeedTextField.setEditable(false);

        jMenu1.setText("File");

        mainItem.setText("Record");
        mainItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAction(evt);
            }
        });
        jMenu1.add(mainItem);

        optionsItem2.setText("Options");
        optionsItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsAction(evt);
            }
        });
        jMenu1.add(optionsItem2);

        exitItem2.setText("Exit");
        exitItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAction(evt);
            }
        });
        jMenu1.add(exitItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(localeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfileRadioButton)
                            .addComponent(databaseRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(dateLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(avTempLabel)
                            .addComponent(avSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avSpeedTextField)
                            .addComponent(avTempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(searchButton)
                        .addGap(52, 52, 52)
                        .addComponent(backButton)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(localeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(databaseRadioButton)
                        .addGap(1, 1, 1)
                        .addComponent(textfileRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avTempLabel)
                            .addComponent(avTempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avSpeedLabel)
                            .addComponent(avSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(backButton))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1startReading(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1startReading
        
    }//GEN-LAST:event_jButton1startReading

    private void jButton2stopReading(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2stopReading
       
    }//GEN-LAST:event_jButton2stopReading

    private void tempComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempComboActionPerformed

    }//GEN-LAST:event_tempComboActionPerformed

    //Return to the stats page
    private void statsAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsAction
        // TODO add your handling code here:
    }//GEN-LAST:event_statsAction

    //Exit the Application
    private void exitAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAction
        System.exit(0);
    }//GEN-LAST:event_exitAction

    //Return to the main capture page
    private void mainAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAction
        this.dispose();
    }//GEN-LAST:event_mainAction

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        if(textfileRadioButton.isSelected()) {
            //Remove any previous data in the table
            if(model.getRowCount()>0) {
                for(int j=model.getRowCount()-1; j>-1; j-- ) {
                    model.removeRow(j);
                }
            }
            textRead.setReadFrom(dateField.getText());     //Reads number of lines in file

            int i = 0;                        //
            tableData = textRead.getMatrix(); //Let the tableData equal the return value of getMatrix            
            while(i < textRead.getFileLines())
            {            
                row = tableData[i];
                model.addRow(row);
                i++;
            }
            
            //Get the average temperature value
            avTempTextField.setText(
                                        tempAvg.setAverageTemperature(
                                        tableData, textRead.getFileLines())
                                       );
            
            //Get the average wind speed value
            avSpeedTextField.setText(
                                        speedAvg.setAverageSpeed(
                                        tableData, textRead.getFileLines())
                                       );
        } //End if
        
        if(databaseRadioButton.isSelected()) { 
            //Remove any previous data in the table
            if(model.getRowCount()>0) {
                for(int j=model.getRowCount()-1; j>-1; j-- ) {
                    model.removeRow(j);
                }
            }
            
            System.out.println( dbRead.getRowCount(dateField.getText()) );

            dbRead.jdbcRead(dateField.getText()); 
            int i = 0;                          //
            tableData = dbRead.getSearchData(); //Let the tableData equal the return value of getMatrix
            while(i < dbRead.getRowCount(dateField.getText()))
            {            
                row = tableData[i];
                model.addRow(row);
                i++;
            }
            
            //Get the average temperature value
            avTempTextField.setText(
                                        tempAvg.setAverageTemperature(
                                        tableData, dbRead.getRowCount(dateField.getText()))
                                       );
            
            //Get the average wind speed value
            avSpeedTextField.setText(
                                        speedAvg.setAverageSpeed(
                                        tableData, dbRead.getRowCount(dateField.getText()))
                                       );
        }
    }//GEN-LAST:event_searchActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LocaleButtonGroup;
    private javax.swing.JLabel avSpeedLabel;
    private javax.swing.JTextField avSpeedTextField;
    private javax.swing.JLabel avTempLabel;
    private javax.swing.JTextField avTempTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton databaseRadioButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuItem exitItem2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel localeLabel;
    private javax.swing.JMenuItem mainItem;
    private javax.swing.JMenuItem optionsItem2;
    private javax.swing.JMenuItem recordItem;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JMenuItem statsItem;
    private javax.swing.JComboBox tempCombo;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JRadioButton textfileRadioButton;
    private javax.swing.JComboBox windCombo;
    private javax.swing.JTextField windField;
    private javax.swing.JLabel windLabel;
    // End of variables declaration//GEN-END:variables
}
